runtime: python312

entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  TM_API_KEY: "YOUR_TM_API_KEY_HERE"
  GOOGLE_MAPS_KEY: "YOUR_GOOGLE_MAPS_KEY_HERE"
  IPINFO_TOKEN: "YOUR_IPINFO_TOKEN_HERE"

instance_class: F1
